using System;

namespace CSFundamentals.Sedgewick.Chapter1.Section2;

/*
 * Gaussian Random Numbers (Box–Muller Method)
 *
 * Write a program RandomGaussian that prints a random number r drawn from
 * the standard Gaussian (normal) distribution.
 *
 * One way to do this is using the Box–Muller formula:
 *
 *   r = sin(2 * π * v) * sqrt(-2 * ln(u))
 *
 * Where:
 *   - u and v are independent random numbers uniformly distributed between 0 and 1.
 *   - Use Math.Random() to generate u and v.
 *   - The resulting value r will follow a standard normal distribution (mean = 0, std dev = 1).
 *
 * Example Output:
 *   r = 0.352765014177792
 *
 * Note:
 *   - This is one of two values generated by Box–Muller; only one is used here.
 */

public class Exercise2_27
{
    public Exercise2_27() { }
    public void Run()
    {
        var seed = new Random();
        var v = seed.NextDouble();
        var u = seed.NextDouble();
        var sinValue = Math.Sin(2 * Math.PI * v);
        var inverseValue = -2 * Math.Log(u);
        var inverse = Math.Pow(inverseValue, 0.5);
        var expression = sinValue * inverse;

        System.Console.WriteLine($"random value = {expression:F3}");
    }
}
